import numpy as np
import matplotlib.pyplot as plt
import sys
import os

# Import the full-diagonalization post-processing helper.
#
# FullDiagPurger filters and organizes eigenvalues, eigenvectors, 
# and weights from full-diagonalization data.
import mrock.FullDiagPurger as fdp

# Import data-loading utilities and parameter helper functions.
# This includes DataLoader and continuum_params.
from mrock.get_data import *

# Create a global DataLoader instance.
# By default, this will look for data in the package's default data directory
# or in the directory specified by the MROCK_DATA_DIR environment variable.
data_loader = DataLoader()


def load_data(name):
    """Returns the data for the LatticeCUT test case with the given name.

    Available names
    ---------------
    standard
        Superconducting lattice with g = 2.5.

        This data set is used for visualizing secondary excitations in the
        full-diagonalization eigenvectors.

    enhanced
        BCC-like data set with g = 1.5 and U = 0.2.

        This data set is used for visualizing an enhanced mode in the spectral
        response.
    """

    # Each branch below loads one specific LatticeCUT data set.
    #
    # The data are stored under:
    #
    #     data / lattice_cut / <subdir> / parameter-folders / full_diagonalization.json.gz
    #
    # The exact parameter-folder path is generated by lattice_cut_params(...).
    #
    # Here:
    #
    # - N is the number of discretization points,
    # - g is the attractive coupling,
    # - U is an interaction parameter,
    # - E_F is the Fermi energy,
    # - omega_D is the Debye frequency or cutoff scale.

    if name == "standard":
        # Load the standard superconducting LatticeCUT test case.
        #
        # This data set uses:
        #
        # - N = 2000 grid points,
        # - g = 2.5,
        # - U = 0,
        # - E_F = 0,
        # - omega_D = 0.02.
        return data_loader.load_panda(
            model="lattice_cut",
            subdir=os.path.join("test", "sc"),
            file="full_diagonalization.json.gz",
            **lattice_cut_params(
                N=2000,
                g=2.5,
                U=0.,
                E_F=0,
                omega_D=0.02
            )
        )

    elif name == "enhanced":
        # Load the enhanced-mode LatticeCUT test case.
        #
        # This data set uses:
        #
        # - N = 2000 grid points,
        # - g = 1.5,
        # - U = 0.2,
        # - E_F = -0.5,
        # - omega_D = 0.02.
        return data_loader.load_panda(
            model="lattice_cut",
            subdir=os.path.join("test", "bcc"),
            file="full_diagonalization.json.gz",
            **lattice_cut_params(
                N=2000,
                g=1.5,
                U=0.2,
                E_F=-0.5,
                omega_D=0.02
            )
        )

    else:
        # Stop with a clear error if the user requests an unknown test case.
        raise ValueError("Continuum test: Invalid index")


def create_plot(name):
    """Load one LatticeCUT test case and create the corresponding plot."""

    # Load the selected full-diagonalization data set.
    #
    # main_df contains the full-diagonalization eigenvalues, weights,
    # eigenvectors, continuum boundaries, chemical potential, and other
    # metadata needed for plotting.
    main_df = load_data(name)

    if name == "standard":
        # The "standard" case visualizes eigenvectors of the amplitude/Higgs
        # and phase modes.
        #
        # Three vertically stacked axes are used:
        #
        # - axes[0]: first component of the amplitude/Higgs eigenvector,
        # - axes[1]: second component, interpreted here as occupation-related,
        # - axes[2]: phase eigenvector.
        fig, axes = plt.subplots(nrows=3, sharex=True)
        fig.subplots_adjust(hspace=0)

        axes[0].set_ylabel("Higgs")
        axes[1].set_ylabel("Occupation")
        axes[2].set_ylabel("Phase")
        axes[-1].set_xlabel(r"$\varepsilon - \mu$")
        axes[0].set_xlim(-0.25, 0.25)

        # Construct the epsilon grid used for plotting the eigenvectors.
        #
        # The raw grid is np.linspace(-1, 1, 2000). The chemical potential is
        # subtracted so that the x-axis is centered around epsilon - mu.
        epsilon_space = np.linspace(-1, 1, 2000) - main_df["chemical_potential"]

        # Create a FullDiagPurger object.
        #
        # This post-processes the full-diagonalization data:
        #
        # - removes likely numerical artifacts,
        # - separates amplitude and phase modes,
        # - detects nearly degenerate doublets,
        # - sign-normalizes eigenvectors for consistent plotting.
        #
        # The filtering thresholds can be configured explicitly:
        #
        # - peak_diff_tol controls when nearby peaks are merged and when
        #   amplitude-phase modes are considered near-degenerate doublets,
        # - artifact_weight_cutoff removes tiny numerical-weight artifacts,
        # - weak_peak_weight_cutoff skips weak later peaks after at least one
        #   candidate peak has already been accepted.
        #
        # The values shown here are the defaults and may be omitted.
        purger = fdp.FullDiagPurger(
            main_df,
            epsilon_space,
            peak_diff_tol=0.004,
            artifact_weight_cutoff=1e-16,
            weak_peak_weight_cutoff=1e-8,
        )

        # Plot the amplitude/Higgs eigenvectors.
        #
        # The amplitude eigenvectors have two components, so axes[:2] is passed.
        # With combined_norm=True, both components are normalized with the same
        # normalization factor.
        purger.plot_amplitude(axes[:2], combined_norm=True)

        # Plot the phase eigenvectors on the third axis.
        #
        # The label "Result" is passed to Matplotlib and can be used in a
        # legend if one is added.
        purger.plot_phase(axes[2], label="Result")

    elif name == "enhanced":
        # The "enhanced" case visualizes spectral functions reconstructed
        # directly from full-diagonalization eigenvalues and weights.
        fig, ax = plt.subplots()

        # Set axis labels.
        ax.set_xlabel(r"$\omega$")
        ax.set_ylabel(r"$A (\omega)$")

        # Construct the complex frequency grid.
        #
        # The real part runs from 0 to 0.4.
        # A small positive imaginary part, eta = 5e-3, is added:
        #
        #     omega -> omega + i eta
        #
        # This broadens discrete spectral peaks and produces smooth plotted
        # curves.
        omegas = np.linspace(0., 0.4, 5000, dtype=complex) + 5e-3j

        # Reconstruct the phase spectral density from eigenvalues and weights.
        #
        # For each complex frequency z, the response is computed as a sum over
        # modes of the form:
        #
        #     weight_n / (z^2 - eigenvalue_n^2)
        #
        # The spectral density is then
        #
        #     A(omega) = -1 / pi * Im(response).
        A_phase = -np.imag(np.array([
            np.sum(
                main_df["phase.weights"]
                / (z**2 - main_df["phase.eigenvalues"]**2)
            )
            for z in omegas
        ])) / np.pi

        # Reconstruct the amplitude/Higgs spectral density in the same way,
        # using the amplitude eigenvalues and weights.
        A_higgs = -np.imag(np.array([
            np.sum(
                main_df["amplitude.weights"]
                / (z**2 - main_df["amplitude.eigenvalues"]**2)
            )
            for z in omegas
        ])) / np.pi

        ax.plot(omegas.real, A_higgs, label="Higgs")
        ax.plot(omegas.real, A_phase, label="Phase")

        ax.set_ylim(0, 0.7)
        ax.legend()

    fig.suptitle(f"LatticeCUT: {name}")
    fig.savefig(f"test_result_{name}.pdf")


# Command-line interface:
#
# If the script is run with an additional argument, that argument is interpreted
# as the LatticeCUT test case to plot.
#
# Example:
#
#     python plot_lattice_cut.py standard
#
# or:
#
#     python plot_lattice_cut.py enhanced
#
# If no argument is provided, print a short instruction instead.
if len(sys.argv) > 1:
    create_plot(sys.argv[1])
else:
    print("Please provide the name of the test you would like to plot.")