# DefaultCompilerFlags.cmake

function(SET_COMPILER_FLAGS TARGET)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        if(CMAKE_BUILD_TYPE STREQUAL "Debug")
            target_compile_options(${TARGET} PRIVATE -Wall -Wno-sign-compare  -march=native -O0 -g)
        else()
            target_compile_options(${TARGET} PRIVATE -Wall -Wno-sign-compare  -march=native -O3 -ffast-math)
            target_compile_definitions(${TARGET} PRIVATE NDEBUG)
            SET_MKL_FLAGS(${TARGET})
        endif()
    else()
        message(FATAL_ERROR "Unsupported compiler ${CMAKE_CXX_COMPILER_ID}. Only GCC|Clang is supported.")
    endif()
endfunction()